routes:
  /authors/: routes/authors
  /tags/: routes/tags
  /thanks/: routes/thanks

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tags/{slug}/
  author: /authors/{slug}/
